version: 2
jobs:
  build:
    machine: true
    environment:
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      PRIVATE_REGISTRY: us.gcr.io/code_climate

    steps:
      # CircleCI 2.0 doesn't expand env vars yet so we have to do it manually.
      - run:
          name: Env
          command: |
            echo 'export IMAGE_NAME="${PRIVATE_REGISTRY}/${CIRCLE_PROJECT_REPONAME}:b${CIRCLE_BUILD_NUM}"' >> ${BASH_ENV}
      - checkout
      - run:
          name: Build image
          command: make image
      - run:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo $gcloud_json_key_base64 | sed 's/ //g' | base64 -d > /tmp/gcloud_key.json
              curl https://sdk.cloud.google.com | bash
              gcloud auth activate-service-account --key-file /tmp/gcloud_key.json
              gcloud docker -a
              docker push ${IMAGE_NAME}
            fi

notify:
  webhooks:
    - url: https://cc-slack-proxy.herokuapp.com/circle
